language: android
jdk: oraclejdk8

sudo: true

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

android:
  components:

    - platform-tools
    - tools

    # The BuildTools version
    - build-tools-25.0.2

    # The SDK version
    - android-25

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25

    - sys-img-armeabi-v7a-android-23

  licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
        - ".+"

script: ./gradlew build

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

